### PR TITLE
Update PPZ_RPi_code.py - slowdown exepction

### PR DESCRIPTION
**Pull request by ztr-pen**
I was getting an exception on first boot. As there is no timeout the error filled the screen with the current temp and increased the temperature of the pi.

### CODE REVIEW

**Comment by ztr-pen** [comment]
The error was also preventing from the battery voltage from showing on first boot.

**Comment by DavidMurrayP2P** [comment]
I have seen this before. Are you using a 64 bit PiOS image? It works with both 32 bit and 64 bit but there are some minor changes: https://github.com/DavidMurrayP2P/PhotonPowerZero/blob/main/USERDOCS.md

Can you try: 

sudo apt remove python3-rpi.gpio
sudo apt install python3-rpi-lgpio

Then reboot

**Review by DavidMurrayP2P — APPROVED** [review]

**Comment by DavidMurrayP2P** [comment]
Thanks for picking up on the lack of a timer in the exception. Much appreciated.

**Comment by ztr-pen** [comment]
Thanks @DavidMurrayP2P, 

I swapped the python gpio packages and everything is now up and running on a li-po battery. Now to purchase a solar panel.

**Comment by DavidMurrayP2P** [comment]
Awesome to hear, pleased that it is working for you. Thanks so much for improving the project with your code contribution.

**Pull request merged**
